steps:
  - label: ":slack: Send Build URL"
    command: echo "Build completed!"
    notify:
      - slack:
          channels:
            - "#tests"
          message: "🔗 Build URL: ${BUILDKITE_BUILD_URL}"


