steps:
  - label: ":slack: Send Build URL"
    command: echo "Build completed!"
    notify:
      - slack:
          channels:
            - "#tests"
          message: "This is the 🔗 Build URL: ${BUILDKITE_BUILD_URL}\n👤 Build created by: ${BUILDKITE_BUILD_CREATOR_EMAIL} "


