notify:
  - slack:
      channels:
        - "your-channel-name"
      message: "🔗 Build URL: ${BUILDKITE_BUILD_URL}\n👤 Build created by: ${BUILDKITE_BUILD_CREATOR_EMAIL}"

steps:
  - label: ":slack: Send Build Information"
    command: echo "Build completed!"
